/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.DefaultTableCellRenderer;


public class StudentReport extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String pass = "root";
    private static final String url = "jdbc:mysql://localhost:3307/mini_project";
    
   ResultSet rs = null;
   ResultSet rs1 = null;
   ResultSet rs2 = null;
    String s;
    String s1;
    public StudentReport(String login,String stud) {
        initComponents();
        this.s = login;
        this.s1 = stud;
        
        jTableReport.setOpaque(false);
    ((DefaultTableCellRenderer)jTableReport.getDefaultRenderer(Object.class)).setOpaque(false);
    jTableReport.setShowGrid(true);
    
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonReport = new javax.swing.JButton();
        jButtonDetails = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jLabelStudentReport = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReport = new javax.swing.JTable();
        jButtonShowAll = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelTotalPresent = new javax.swing.JLabel();
        jLabelTotalAbsent = new javax.swing.JLabel();
        jLabelPercentage = new javax.swing.JLabel();
        jTextFieldPresent = new javax.swing.JTextField();
        jTextFieldAbsent = new javax.swing.JTextField();
        jTextFieldPercentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Student/Images/IMG_9761.PNG"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dashboard");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jButtonReport.setText("Report");
        jButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportActionPerformed(evt);
            }
        });

        jButtonDetails.setText("Details");
        jButtonDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetailsActionPerformed(evt);
            }
        });

        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(89, 89, 89)
                .addComponent(jButtonReport)
                .addGap(35, 35, 35)
                .addComponent(jButtonDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogOut)
                .addContainerGap())
        );

        jLabelStudentReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStudentReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStudentReport.setText("Student Report");

        jLabelDate.setText("Date:");

        jTextFieldDate.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldDate.setText("YYYY-MM-DD");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusLost(evt);
            }
        });
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });

        jButtonFilter.setText("Filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jTableReport.setForeground(new java.awt.Color(255, 255, 255));
        jTableReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableReport);

        jButtonShowAll.setText("Show All");
        jButtonShowAll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonShowAllFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonShowAllFocusLost(evt);
            }
        });
        jButtonShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jLabelTotalPresent.setText("Total Present:");

        jLabelTotalAbsent.setText("Total Absent:");

        jLabelPercentage.setText("Percentage:");

        jTextFieldPresent.setEditable(false);

        jTextFieldAbsent.setEditable(false);

        jTextFieldPercentage.setEditable(false);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelStudentReport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonShowAll, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonClear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTotalPresent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTotalAbsent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelPercentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldPresent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldAbsent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldPercentage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jLabelStudentReport, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jButtonFilter)))
                                .addGap(132, 132, 132)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(jLabelTotalPresent)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldPresent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(jLabelTotalAbsent)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabelPercentage)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButtonShowAll)
                                .addGap(175, 175, 175)
                                .addComponent(jButtonClear)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStudentReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDate)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTotalPresent)
                            .addComponent(jTextFieldPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFilter)
                    .addComponent(jLabelTotalAbsent)
                    .addComponent(jTextFieldAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPercentage)
                    .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowAll)
                    .addComponent(jButtonClear))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetailsActionPerformed
        new StudentDetails(s,s1).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDetailsActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        new StudentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportActionPerformed

    private void jButtonShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllActionPerformed
       
        
        try
        {
            Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select * from attendance where stud_id=?";
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, s1);
           
           ResultSet rs = st.executeQuery();
          DefaultTableModel model = (DefaultTableModel)jTableReport.getModel();
          //jTextFieldDate.setText(null);
          
          while(model.getRowCount()>0)
        {
            for(int i = 0;i<model.getRowCount();i++)
            {
                model.removeRow(i);
            }
        }
           while(rs.next())
           {
               String att = rs.getString("stud_attendance");
               String date = rs.getString("date");
               
               String tbData[] = {date,att};
               DefaultTableModel tblModel = (DefaultTableModel)jTableReport.getModel();
               
               //Add data
               tblModel.addRow(tbData);
           }
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        int p,a,c;
        double r,d;
        try
        {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select count(*) from attendance where stud_attendance='Present'and stud_id = ?";
           PreparedStatement st2 = conn.prepareStatement(sql);
           st2.setString(1, s1);
           ResultSet rs2 = st2.executeQuery();
           while(rs2.next())
           {
               jTextFieldPresent.setText(rs2.getString("count(*)"));
           }
           
           String sql1 = "select count(*) from attendance where stud_attendance='Absent' and stud_id=?";
           PreparedStatement st1 = conn.prepareStatement(sql1);
           st1.setString(1, s1);
           ResultSet rs1 = st1.executeQuery();
           while(rs1.next())
           {
               jTextFieldAbsent.setText(rs1.getString("count(*)"));
           }
           p = Integer.parseInt(jTextFieldPresent.getText());
           a = Integer.parseInt(jTextFieldAbsent.getText());
           c = p+a;
           d =(p*100.0);
           r= d/c;
           
           jTextFieldPercentage.setText(String.valueOf(r)+"%");
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonShowAllActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        
        jTextFieldPresent.setText(null);
        jTextFieldAbsent.setText(null);
        jTextFieldPercentage.setText(null);
       jTextFieldDate.setText(null);
        DefaultTableModel model = (DefaultTableModel)jTableReport.getModel();
        while(model.getRowCount()>0)
        {
            for(int i = 0;i<model.getRowCount();i++)
            {
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        jTextFieldPercentage.setText(null);
        try
        {
            Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select * from attendance where stud_id=? and date=?";
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, s1);
           st.setString(2, jTextFieldDate.getText());
           ResultSet rs = st.executeQuery();
          DefaultTableModel model = (DefaultTableModel)jTableReport.getModel(); 
          while(model.getRowCount()>0)
        {
            for(int i = 0;i<model.getRowCount();i++)
            {
                model.removeRow(i);
            }
        }
           while(rs.next())
           {
               String att = rs.getString("stud_attendance");
               String date = rs.getString("date");
               
               String tbData[] = {date,att};
               DefaultTableModel tblModel = (DefaultTableModel)jTableReport.getModel();
               
               //Add data
               tblModel.addRow(tbData);
           }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try
        {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select count(*) from attendance where stud_attendance='Present'and stud_id = ? and date=?";
           PreparedStatement st2 = conn.prepareStatement(sql);
           st2.setString(1, s1);
           st2.setString(2, jTextFieldDate.getText());
           ResultSet rs2 = st2.executeQuery();
           while(rs2.next())
           {
               jTextFieldPresent.setText(rs2.getString("count(*)"));
           }
           
           String sql1 = "select count(*) from attendance where stud_attendance='Absent' and stud_id=? and date=?";
           PreparedStatement st1 = conn.prepareStatement(sql1);
           st1.setString(1, s1);
           st1.setString(2, jTextFieldDate.getText());
           ResultSet rs1 = st1.executeQuery();
           while(rs1.next())
           {
               jTextFieldAbsent.setText(rs1.getString("count(*)"));
           }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        if(jTextFieldDate.getText().equals("YYYY-MM-DD"))
        {
            jTextFieldDate.setText("");
            jTextFieldDate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jTextFieldDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusLost
        if(jTextFieldDate.getText().equals(""))
        {
            jTextFieldDate.setText("YYYY-MM-DD");
            jTextFieldDate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jTextFieldDateFocusLost

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jButtonShowAllFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonShowAllFocusGained
        if(jTextFieldDate.getText().equals("YYYY-MM-DD"))
        {
            jTextFieldDate.setText("");
            jTextFieldDate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jButtonShowAllFocusGained

    private void jButtonShowAllFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonShowAllFocusLost
       if(jTextFieldDate.getText().equals(""))
        {
            jTextFieldDate.setText("YYYY-MM-DD");
            jTextFieldDate.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jButtonShowAllFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReport(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDetails;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonReport;
    private javax.swing.JButton jButtonShowAll;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelPercentage;
    private javax.swing.JLabel jLabelStudentReport;
    private javax.swing.JLabel jLabelTotalAbsent;
    private javax.swing.JLabel jLabelTotalPresent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableReport;
    private javax.swing.JTextField jTextFieldAbsent;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldPercentage;
    private javax.swing.JTextField jTextFieldPresent;
    // End of variables declaration//GEN-END:variables
}
