/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class CourseAdd extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String pass = "root";
    private static final String url = "jdbc:mysql://localhost:3307/mini_project";
    
    public CourseAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCourse_Id = new javax.swing.JTextField();
        jLabelCourse_Id = new javax.swing.JLabel();
        jLabelCourse_Name = new javax.swing.JLabel();
        jTextFieldCourse_name = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAddNewCourse = new javax.swing.JLabel();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCourse_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourse_IdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCourse_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        jLabelCourse_Id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCourse_Id.setText("Course Id");
        getContentPane().add(jLabelCourse_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        jLabelCourse_Name.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCourse_Name.setText("Course Name");
        getContentPane().add(jLabelCourse_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jTextFieldCourse_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourse_nameActionPerformed(evt);
            }
        });
        jTextFieldCourse_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCourse_nameKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldCourse_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/back-arrow.png"))); // NOI18N
        jButtonBack.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 28, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 69, 330, 10));

        jLabelAddNewCourse.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelAddNewCourse.setText("Add New Course");
        getContentPane().add(jLabelAddNewCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, 110, -1));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/PNG image 3.png"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new CourseInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldCourse_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourse_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourse_nameActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        
        String sql = "insert into course values(?,?)";
        
        try
       {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, jTextFieldCourse_Id.getText());
           st.setString(2, jTextFieldCourse_name.getText());
           
           st.executeUpdate();
           JOptionPane.showMessageDialog(null, "Course Added Successfully","Alert",JOptionPane.INFORMATION_MESSAGE);
       }
       catch(SQLException e)
       {
           System.out.println(e);
           JOptionPane.showMessageDialog(null, "Course Registration Failed","Error",JOptionPane.ERROR_MESSAGE);
       } 
        new CourseInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jTextFieldCourse_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourse_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourse_IdActionPerformed

    private void jTextFieldCourse_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCourse_nameKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
           String sql = "insert into course values(?,?)";
        
        try
       {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, jTextFieldCourse_Id.getText());
           st.setString(2, jTextFieldCourse_name.getText());
           
           st.executeUpdate();
           JOptionPane.showMessageDialog(null, "Course Added Successfully","Alert",JOptionPane.INFORMATION_MESSAGE);
       }
       catch(SQLException e)
       {
           System.out.println(e);
       } 
        new CourseInfo().setVisible(true);
        this.setVisible(false);
       }
    }//GEN-LAST:event_jTextFieldCourse_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JLabel jLabelAddNewCourse;
    private javax.swing.JLabel jLabelCourse_Id;
    private javax.swing.JLabel jLabelCourse_Name;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCourse_Id;
    private javax.swing.JTextField jTextFieldCourse_name;
    // End of variables declaration//GEN-END:variables
}
