/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import Student.StudentLogin;
import Teacher.TeacherLogin;
/**
 *
 * @author Swaraj
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelWelcomeToXie = new javax.swing.JLabel();
        jButtonAdmin = new javax.swing.JButton();
        jButtonTeacher = new javax.swing.JButton();
        jButtonStudent = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 42, 240, 10));

        jLabelWelcomeToXie.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelWelcomeToXie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeToXie.setText("WELCOME TO XIE");
        getContentPane().add(jLabelWelcomeToXie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 260, -1));

        jButtonAdmin.setBackground(new java.awt.Color(255, 153, 153));
        jButtonAdmin.setText("ADMIN");
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 87, -1));

        jButtonTeacher.setBackground(new java.awt.Color(255, 153, 153));
        jButtonTeacher.setText("TEACHER");
        jButtonTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeacherActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jButtonStudent.setBackground(new java.awt.Color(255, 153, 153));
        jButtonStudent.setText("STUDENT");
        jButtonStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/Homepage.jpg"))); // NOI18N
        jLabelWallpaper.setMaximumSize(new java.awt.Dimension(407, 200));
        jLabelWallpaper.setMinimumSize(new java.awt.Dimension(407, 200));
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 400, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jButtonTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeacherActionPerformed
       new TeacherLogin().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonTeacherActionPerformed

    private void jButtonStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentActionPerformed
        new StudentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonStudent;
    private javax.swing.JButton jButtonTeacher;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JLabel jLabelWelcomeToXie;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
