/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Swaraj
 */
public class Pincode extends javax.swing.JFrame {

    /**
     * Creates new form Pincode
     */
    public Pincode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPincode = new javax.swing.JLabel();
        jPasswordFieldPincode = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelSecurityPin = new javax.swing.JLabel();
        jButtonGo = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPincode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelPincode.setForeground(new java.awt.Color(255, 51, 51));
        jLabelPincode.setText("Pincode");
        getContentPane().add(jLabelPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 74, -1, -1));

        jPasswordFieldPincode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPincodeKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 71, 40, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 43, 127, 10));

        jLabelSecurityPin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelSecurityPin.setForeground(new java.awt.Color(255, 51, 51));
        jLabelSecurityPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSecurityPin.setText("Security Pin");
        getContentPane().add(jLabelSecurityPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 20, 127, -1));

        jButtonGo.setText("Go");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/Pincode 3.jpg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 220, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        if(new String(jPasswordFieldPincode.getText()).equals("1318")) {
            new SignUp().setVisible(true);
            new SignIn().setVisible(false);
            this.setVisible(false);
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Invalid Pin", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jPasswordFieldPincodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPincodeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if(new String(jPasswordFieldPincode.getText()).equals("1318")) {
            new SignUp().setVisible(true);
            new SignIn().setVisible(false);
            this.setVisible(false);
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Invalid Pin", "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
        }
        }
    }//GEN-LAST:event_jPasswordFieldPincodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pincode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pincode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pincode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pincode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pincode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGo;
    private javax.swing.JLabel jLabelPincode;
    private javax.swing.JLabel jLabelSecurityPin;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPasswordField jPasswordFieldPincode;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
