/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class SignUp extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String pass = "root";
    private static final String url = "jdbc:mysql://localhost:3307/mini_project";
    
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdminSignUp = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonCreateAccount = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonBack = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAdminSignUp.setBackground(new java.awt.Color(204, 204, 255));
        jLabelAdminSignUp.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabelAdminSignUp.setForeground(new java.awt.Color(0, 255, 0));
        jLabelAdminSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdminSignUp.setText("Admin SignUp");
        getContentPane().add(jLabelAdminSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 51, 302, -1));

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(0, 255, 0));
        jLabelUsername.setText("Username");
        getContentPane().add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 105, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 255, 0));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 151, -1, -1));

        jLabelConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelConfirmPassword.setForeground(new java.awt.Color(0, 255, 0));
        jLabelConfirmPassword.setText("Confirm Password");
        getContentPane().add(jLabelConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 201, -1, -1));

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 99, 177, -1));

        jPasswordFieldConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldConfirmPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 198, 177, -1));
        getContentPane().add(jPasswordFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 148, 177, -1));

        jButtonCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCreateAccount.setText("Create Account");
        jButtonCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 250, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 71, 302, 10));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/back-arrow.png"))); // NOI18N
        jButtonBack.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/1.jpeg"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButtonCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAccountActionPerformed
        
        String sql = "insert into admin values(?,?)";
        if(new String(jPasswordFieldPassword.getText()).equals(new String(jPasswordFieldConfirmPassword.getText())))
        {
        try
       {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, jTextFieldUsername.getText());
           st.setString(2, new String(jPasswordFieldPassword.getText()));
           
           if(new String(jTextFieldUsername.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the username field","Error",JOptionPane.ERROR_MESSAGE);
           }
           
           else if(new String(jPasswordFieldPassword.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the password field","Error",JOptionPane.ERROR_MESSAGE);
           }
           else if(new String(jPasswordFieldConfirmPassword.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the confirm password field","Error",JOptionPane.ERROR_MESSAGE);
           }
           
           else
           {
           JOptionPane.showMessageDialog(null, "SignUp Successful","Alert",JOptionPane.INFORMATION_MESSAGE);
           st.executeUpdate();
           new SignIn().setVisible(true);
           this.setVisible(false);
           }
           
       }
       catch(SQLException e)
       {
           System.out.println(e);
       }
       // new SignIn().setVisible(true);
        //this.setVisible(false);
       }  
       else
        {
           JOptionPane.showMessageDialog(null, "Both Password do not match, PLEASE enter again","Error",JOptionPane.ERROR_MESSAGE);
           jPasswordFieldPassword.setText(null);
           jPasswordFieldConfirmPassword.setText(null);
           
           //new SignUp().setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonCreateAccountActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
           new SignIn().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jPasswordFieldConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmPasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String sql = "insert into admin values(?,?)";
        if(new String(jPasswordFieldPassword.getText()).equals(new String(jPasswordFieldConfirmPassword.getText())))
        {
        try
       {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement st = conn.prepareStatement(sql);
           st.setString(1, jTextFieldUsername.getText());
           st.setString(2, new String(jPasswordFieldPassword.getText()));
           
           if(new String(jTextFieldUsername.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the username field","Error",JOptionPane.ERROR_MESSAGE);
           }
           
           else if(new String(jPasswordFieldPassword.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the password field","Error",JOptionPane.ERROR_MESSAGE);
           }
           else if(new String(jPasswordFieldConfirmPassword.getText()).equals(""))
           {
               JOptionPane.showMessageDialog(null, "Please fill the confirm password field","Error",JOptionPane.ERROR_MESSAGE);
           }
           
           else
           {
           JOptionPane.showMessageDialog(null, "SignUp Successful","Alert",JOptionPane.INFORMATION_MESSAGE);
           st.executeUpdate();
           new SignIn().setVisible(true);
           this.setVisible(false);
           }
           
       }
       catch(SQLException e)
       {
           System.out.println(e);
       }
       // new SignIn().setVisible(true);
        //this.setVisible(false);
       }  
       else
        {
           JOptionPane.showMessageDialog(null, "Both Password do not match, PLEASE enter again","Error",JOptionPane.ERROR_MESSAGE);
           jPasswordFieldPassword.setText(null);
           jPasswordFieldConfirmPassword.setText(null);
           
           //new SignUp().setVisible(true);
        }
        }
    }//GEN-LAST:event_jPasswordFieldConfirmPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreateAccount;
    private javax.swing.JLabel jLabelAdminSignUp;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JPasswordField jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
