/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.*;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;



public class StudentAdd extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String pass = "root";
    private static final String url = "jdbc:mysql://localhost:3307/mini_project";
    ResultSet rs = null;
    ResultSet rs2 = null;
    
    
    public StudentAdd() {
        initComponents();
        
    jTableCourse1.setOpaque(false);
    ((DefaultTableCellRenderer)jTableCourse1.getDefaultRenderer(Object.class)).setOpaque(false);
    jTableCourse1.setShowGrid(true);
    jScrollPane3.setOpaque(false);
    jScrollPane3.getViewport().setOpaque(false);
    
    jTableTeacher.setOpaque(false);
    ((DefaultTableCellRenderer)jTableTeacher.getDefaultRenderer(Object.class)).setOpaque(false);
    jTableTeacher.setShowGrid(true);
    
    jScrollPane4.setOpaque(false);
    jScrollPane4.getViewport().setOpaque(false);
    
    try
        {
            Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select * from course";
           PreparedStatement st = conn.prepareStatement(sql);
           ResultSet rs = st.executeQuery();
           
           while(rs.next())
           {
               String Course_ID = rs.getString("course_id");
               String course_Name = rs.getString("course_name");
      
               String tbData[] = {Course_ID,course_Name};
               DefaultTableModel tblModel = (DefaultTableModel)jTableCourse1.getModel();
               
               //Add data
               tblModel.addRow(tbData);
           }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
         
        try
        {
            Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select * from teacher";
           PreparedStatement st = conn.prepareStatement(sql);
           ResultSet rs = st.executeQuery();
           
           while(rs.next())
           {
               String Teacher_ID = rs.getString("f_id");
               String Teacher_Name = rs.getString("t_name");
      
               String tbData[] = {Teacher_ID,Teacher_Name};
               DefaultTableModel tblModel = (DefaultTableModel)jTableTeacher.getModel();
               
               //Add data
               tblModel.addRow(tbData);
           }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
        try
       {
           String sql2 = "select * from batch";
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement pst = conn.prepareStatement(sql2);
           rs = pst.executeQuery();
           while(rs.next())
           {
               jComboBoxBatchCode.addItem(rs.getString("batch_code"));
           }
           
       }
        
        catch(SQLException e)
       {
           System.out.println(e);
       }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelAdd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelMiddleName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jLabelEmailId = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldFatherName = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldEmailId = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelStudent_ID = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelPh_No = new javax.swing.JLabel();
        jTextFieldPh_No = new javax.swing.JTextField();
        jLabelMother_Name = new javax.swing.JLabel();
        jTextFieldMotherName = new javax.swing.JTextField();
        jLabelDateOfAdmission = new javax.swing.JLabel();
        jLabelBranch = new javax.swing.JLabel();
        jTextFieldStudent_Id = new javax.swing.JTextField();
        jDateChooserDOB = new com.toedter.calendar.JDateChooser();
        jDateChooserDateOfAdmission = new com.toedter.calendar.JDateChooser();
        jComboBoxBranch = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelBatchCode = new javax.swing.JLabel();
        jComboBoxBatchCode = new javax.swing.JComboBox<>();
        jLabelFacultyID = new javax.swing.JLabel();
        jTextFieldFacultyID = new javax.swing.JTextField();
        jLabelFacultyName = new javax.swing.JLabel();
        jTextFieldBatchDays = new javax.swing.JTextField();
        jLabelCourseID = new javax.swing.JLabel();
        jTextFieldCourseID = new javax.swing.JTextField();
        jLabelCourseName = new javax.swing.JLabel();
        jTextFieldBatchTime = new javax.swing.JTextField();
        jLabelCoursesAvailable = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCourse1 = new javax.swing.JTable();
        jLabelTeachers = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTeacher = new javax.swing.JTable();
        jLabelWallpaper = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1320, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAdd.setFont(new java.awt.Font(".SF NS Text", 1, 13)); // NOI18N
        jLabelAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAdd.setText("Add New Student");
        getContentPane().add(jLabelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 51, 761, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 76, 761, 10));

        jLabelFirstName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelFirstName.setText("First Name");
        getContentPane().add(jLabelFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 171, -1, -1));

        jLabelMiddleName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelMiddleName.setText("Father's Name");
        getContentPane().add(jLabelMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 231, -1, -1));

        jLabelLastName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelLastName.setText("Last Name");
        getContentPane().add(jLabelLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 171, 80, -1));

        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setContentAreaFilled(false);
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 341, -1, -1));

        jLabelGender.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelGender.setText("Gender");
        getContentPane().add(jLabelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 345, -1, -1));

        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setContentAreaFilled(false);
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 341, -1, -1));

        buttonGroup1.add(jRadioButtonOther);
        jRadioButtonOther.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButtonOther.setText("Other");
        jRadioButtonOther.setContentAreaFilled(false);
        jRadioButtonOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtherActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 341, -1, -1));

        jLabelEmailId.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelEmailId.setText("Email ID");
        getContentPane().add(jLabelEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 401, -1, -1));

        jLabelAddress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelAddress.setText("Address");
        getContentPane().add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 482, -1, -1));

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 452, 255, -1));

        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 164, 230, 30));

        jTextFieldFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFatherNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 224, 230, 30));

        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 163, 230, 32));

        jTextFieldEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 394, 250, 30));

        jButtonCreate.setText("Create ");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 410, -1, -1));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/back-arrow.png"))); // NOI18N
        jButtonBack.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelStudent_ID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelStudent_ID.setText("Student ID");
        getContentPane().add(jLabelStudent_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 112, -1, -1));

        jLabelDOB.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelDOB.setText("DOB");
        getContentPane().add(jLabelDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 290, 60, -1));

        jLabelPh_No.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelPh_No.setText("Ph.No ");
        getContentPane().add(jLabelPh_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 576, -1, -1));
        getContentPane().add(jTextFieldPh_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 576, 255, 30));

        jLabelMother_Name.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelMother_Name.setText("Mother's Name");
        getContentPane().add(jLabelMother_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jTextFieldMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotherNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMotherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 223, 231, 32));

        jLabelDateOfAdmission.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelDateOfAdmission.setText("Date of Admission");
        getContentPane().add(jLabelDateOfAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        jLabelBranch.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelBranch.setText("Branch");
        getContentPane().add(jLabelBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));
        getContentPane().add(jTextFieldStudent_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 105, 230, 30));

        jDateChooserDOB.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(jDateChooserDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 230, 30));

        jDateChooserDateOfAdmission.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(jDateChooserDateOfAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 170, 30));

        jComboBoxBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "COMPS", "IT ", "EXTC" }));
        jComboBoxBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBranchActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assigning Batch");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 120, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 60, 120, 30));

        jLabelBatchCode.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelBatchCode.setText("Batch Code");
        getContentPane().add(jLabelBatchCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 106, -1, 20));

        jComboBoxBatchCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBoxBatchCode.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxBatchCodePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBoxBatchCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 220, -1));

        jLabelFacultyID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelFacultyID.setText("Faculty ID");
        getContentPane().add(jLabelFacultyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 166, -1, 20));

        jTextFieldFacultyID.setEditable(false);
        getContentPane().add(jTextFieldFacultyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 220, -1));

        jLabelFacultyName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelFacultyName.setText("Batch Days");
        getContentPane().add(jLabelFacultyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 226, -1, 20));

        jTextFieldBatchDays.setEditable(false);
        jTextFieldBatchDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBatchDaysActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBatchDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 220, -1));

        jLabelCourseID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCourseID.setText("Course ID");
        getContentPane().add(jLabelCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 286, -1, 20));

        jTextFieldCourseID.setEditable(false);
        getContentPane().add(jTextFieldCourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 220, -1));

        jLabelCourseName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCourseName.setText("Batch Time");
        getContentPane().add(jLabelCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 336, -1, 20));

        jTextFieldBatchTime.setEditable(false);
        getContentPane().add(jTextFieldBatchTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 220, -1));

        jLabelCoursesAvailable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCoursesAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCoursesAvailable.setText("Courses Available");
        getContentPane().add(jLabelCoursesAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 160, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 160, 20));

        jTableCourse1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTableCourse1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course_ID", "Course_Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCourse1.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTableCourse1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 320, 200));

        jLabelTeachers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTeachers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTeachers.setText("Teachers");
        getContentPane().add(jLabelTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 80, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, 80, 10));

        jTableTeacher.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTableTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Teacher Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTeacher.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(jTableTeacher);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 320, 200));

        jLabelWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/PNG image 3.png"))); // NOI18N
        getContentPane().add(jLabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 1300, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jRadioButtonOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonOtherActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailIdActionPerformed

    private void jTextFieldFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFatherNameActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        String sql = "insert into student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try
       {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           PreparedStatement st = conn.prepareStatement(sql);
           st.setInt(1, Integer.parseInt(jTextFieldStudent_Id.getText()));
           st.setString(2, jTextFieldFirstName.getText());
           st.setString(3, jTextFieldFatherName.getText());
           st.setString(4, jTextFieldLastName.getText());
           st.setString(5, jTextFieldMotherName.getText());
           
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String date = sdf.format(jDateChooserDOB.getDate());
           st.setString(6,date);
        
           if(jRadioButtonMale.isSelected()) {
            st.setString(7,jRadioButtonMale.getText());
        }
        
        else if(jRadioButtonFemale.isSelected()) {
            st.setString(7,jRadioButtonFemale.getText());
        }
        
        else if(jRadioButtonOther.isSelected()) {
            st.setString(7,jRadioButtonOther.getText());
        }
           st.setString(8, jTextFieldEmailId.getText());
           st.setString(9, jTextAreaAddress.getText());
           if((jTextFieldPh_No.getText()).length()==10)
           {
               st.setDouble(10, Double.parseDouble(jTextFieldPh_No.getText()));
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Phone Number is not valid","ERROR",JOptionPane.ERROR_MESSAGE);
           }
           
           
           SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
           String dat = sd.format(jDateChooserDateOfAdmission.getDate());
           st.setString(11,dat);
           
           st.setString(12,(String)jComboBoxBranch.getSelectedItem());
           st.setString(13,(String)jComboBoxBatchCode.getSelectedItem());
           String stud_login = (jTextFieldStudent_Id.getText()+"."+ jTextFieldFirstName.getText().toLowerCase() + (jTextFieldLastName.getText().toLowerCase().charAt(0)) + (jTextFieldFatherName.getText().toLowerCase().charAt(0)) + (jTextFieldMotherName.getText().toLowerCase().charAt(0)) + "@student.xavier.ac.in");
           String stud_pass = (jTextFieldFirstName.getText() + jTextFieldStudent_Id.getText());
           st.setString(14, stud_login);
           st.setString(15, stud_pass);
           
           
           st.executeUpdate();
           JOptionPane.showMessageDialog(null, "Student "+jTextFieldFirstName.getText()+" Added Successfully","Alert",JOptionPane.INFORMATION_MESSAGE);
           new StudentInfo().setVisible(true);
           this.setVisible(false);

       }
       catch(SQLException e)
       {
           System.out.println(e);
           JOptionPane.showMessageDialog(null, "Failed To Add Student","ERROR",JOptionPane.ERROR_MESSAGE);
           //new StudentAdd().setVisible(true);
       }
        
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
           new StudentInfo().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotherNameActionPerformed

    private void jComboBoxBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBranchActionPerformed

    private void jComboBoxBatchCodePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxBatchCodePopupMenuWillBecomeInvisible
        
        String tmp = (String)jComboBoxBatchCode.getSelectedItem();
        String sql2 = "select * from batch where batch_code = ?";
        
        try
        {
           Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
      
           PreparedStatement st = conn.prepareStatement(sql2);
           st.setString(1, tmp);
           rs = st.executeQuery();
           while(rs.next())
           {
               String add = rs.getString("f_id");
               jTextFieldFacultyID.setText(add);
               
               String add3 = rs.getString("course_id");
               jTextFieldCourseID.setText(add3);
               
               String add2 = rs.getString("batch_days");
               jTextFieldBatchDays.setText(add2);
               
               String add4 = rs.getString("batch_time");
               jTextFieldBatchTime.setText(add4);
           }  
        
        }
        catch(Exception e)
        {
            System.out.println(e);
            //JOptionPane.showMessageDialog(null, "Failed To Register the Batch","ERROR",JOptionPane.ERROR_MESSAGE);     
        }
    }//GEN-LAST:event_jComboBoxBatchCodePopupMenuWillBecomeInvisible

    private void jTextFieldBatchDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBatchDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBatchDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JComboBox<String> jComboBoxBatchCode;
    private javax.swing.JComboBox<String> jComboBoxBranch;
    private com.toedter.calendar.JDateChooser jDateChooserDOB;
    private com.toedter.calendar.JDateChooser jDateChooserDateOfAdmission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdd;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBatchCode;
    private javax.swing.JLabel jLabelBranch;
    private javax.swing.JLabel jLabelCourseID;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCoursesAvailable;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelDateOfAdmission;
    private javax.swing.JLabel jLabelEmailId;
    private javax.swing.JLabel jLabelFacultyID;
    private javax.swing.JLabel jLabelFacultyName;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMiddleName;
    private javax.swing.JLabel jLabelMother_Name;
    private javax.swing.JLabel jLabelPh_No;
    private javax.swing.JLabel jLabelStudent_ID;
    private javax.swing.JLabel jLabelTeachers;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTableCourse1;
    private javax.swing.JTable jTableTeacher;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldBatchDays;
    private javax.swing.JTextField jTextFieldBatchTime;
    private javax.swing.JTextField jTextFieldCourseID;
    private javax.swing.JTextField jTextFieldEmailId;
    private javax.swing.JTextField jTextFieldFacultyID;
    private javax.swing.JTextField jTextFieldFatherName;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldMotherName;
    private javax.swing.JTextField jTextFieldPh_No;
    private javax.swing.JTextField jTextFieldStudent_Id;
    // End of variables declaration//GEN-END:variables
}
