/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class StudentInfo extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String pass = "root";
    private static final String url = "jdbc:mysql://localhost:3307/mini_project";
    
   ResultSet rs = null;
   
    public StudentInfo() {
        initComponents();
        
        jTableStudent.setOpaque(false);
    ((DefaultTableCellRenderer)jTableStudent.getDefaultRenderer(Object.class)).setOpaque(false);
    jTableStudent.setShowGrid(true);
    
    jScrollPane2.setOpaque(false);
    jScrollPane2.getViewport().setOpaque(false);
    
        try
        {
            Connection conn = null;
           conn = DriverManager.getConnection(url, username, pass);
           
           String sql = "select * from student";
           PreparedStatement st = conn.prepareStatement(sql);
           ResultSet rs = st.executeQuery();
           
           while(rs.next())
           {
               String ID = String.valueOf(rs.getInt("stud_id"));
               String F_Name = rs.getString("f_name");
               String M_Name = rs.getString("m_name");
               String SM_Name = rs.getString("s_mother");
               String L_Name = rs.getString("l_name");
               
               String dob = String.valueOf(rs.getDate("DOB"));
               String gender = rs.getString("Gender");
               String email_id = rs.getString("email_id");
               String address = rs.getString("Address");
               String ph_no = String.valueOf(rs.getLong("Ph_No"));
               String dateofadmission = String.valueOf(rs.getDate("stud_admission"));
               String branch = rs.getString("stud_branch");
               String batch = rs.getString("batch_code");
               String login = rs.getString("student_login");
               String pass = rs.getString("student_pass");
                         
               String tbData[] = {ID,F_Name,M_Name,SM_Name,L_Name,dob,gender,email_id,address,ph_no,dateofadmission,branch,batch,login,pass};
               DefaultTableModel tb2Model = (DefaultTableModel)jTableStudent.getModel();
               
               //Add data
               tb2Model.addRow(tbData);
           }
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonShowData = new javax.swing.JButton();
        jLabelWallpaper = new javax.swing.JLabel();
        jLabelStudent = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabelXIE = new javax.swing.JLabel();
        jButtonStudents = new javax.swing.JButton();
        jButtonTeachers = new javax.swing.JButton();
        jButtonStaff = new javax.swing.JButton();
        jButtonCourses = new javax.swing.JButton();
        jButtonBatch = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelWallpaper2 = new javax.swing.JLabel();
        jLabelWallpaper1 = new javax.swing.JLabel();

        jButtonShowData.setText("Show Data");
        jButtonShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowDataActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 547));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStudent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStudent.setText("STUDENTS");
        getContentPane().add(jLabelStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 1670, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 1670, 10));

        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 50, -1, 30));

        jTableStudent.setBackground(new java.awt.Color(255, 153, 255));
        jTableStudent.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_id", "First Name", "Father's Name", "Mother's Name", "Last Name", "Date of Birth", "Gender", "Email ID", "Address", "Phone Number", "Admission Date", "Branch", "Batch Code", "Login_ID", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false, false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStudent.setGridColor(new java.awt.Color(0, 0, 0));
        jTableStudent.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableStudent);
        if (jTableStudent.getColumnModel().getColumnCount() > 0) {
            jTableStudent.getColumnModel().getColumn(0).setResizable(false);
            jTableStudent.getColumnModel().getColumn(0).setPreferredWidth(13);
            jTableStudent.getColumnModel().getColumn(1).setResizable(false);
            jTableStudent.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTableStudent.getColumnModel().getColumn(2).setResizable(false);
            jTableStudent.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableStudent.getColumnModel().getColumn(3).setResizable(false);
            jTableStudent.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTableStudent.getColumnModel().getColumn(4).setResizable(false);
            jTableStudent.getColumnModel().getColumn(4).setPreferredWidth(15);
            jTableStudent.getColumnModel().getColumn(5).setResizable(false);
            jTableStudent.getColumnModel().getColumn(5).setPreferredWidth(-5);
            jTableStudent.getColumnModel().getColumn(6).setPreferredWidth(30);
            jTableStudent.getColumnModel().getColumn(7).setPreferredWidth(70);
            jTableStudent.getColumnModel().getColumn(8).setPreferredWidth(120);
            jTableStudent.getColumnModel().getColumn(9).setPreferredWidth(30);
            jTableStudent.getColumnModel().getColumn(10).setPreferredWidth(15);
            jTableStudent.getColumnModel().getColumn(11).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1680, 240));

        jLabelXIE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelXIE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/IMG_9761.PNG"))); // NOI18N
        jLabelXIE.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(jLabelXIE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 90));

        jButtonStudents.setBackground(new java.awt.Color(204, 204, 255));
        jButtonStudents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonStudents.setForeground(new java.awt.Color(0, 102, 102));
        jButtonStudents.setText("Students");
        jButtonStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

        jButtonTeachers.setBackground(new java.awt.Color(204, 204, 255));
        jButtonTeachers.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonTeachers.setForeground(new java.awt.Color(0, 102, 102));
        jButtonTeachers.setText("Teachers");
        jButtonTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeachersActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTeachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, -1));

        jButtonStaff.setBackground(new java.awt.Color(204, 204, 255));
        jButtonStaff.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonStaff.setForeground(new java.awt.Color(0, 102, 102));
        jButtonStaff.setText("Staff");
        jButtonStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, -1));

        jButtonCourses.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCourses.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCourses.setForeground(new java.awt.Color(0, 102, 102));
        jButtonCourses.setText("Courses");
        jButtonCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoursesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, -1));

        jButtonBatch.setBackground(new java.awt.Color(204, 204, 255));
        jButtonBatch.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonBatch.setForeground(new java.awt.Color(0, 102, 102));
        jButtonBatch.setText("Batches");
        jButtonBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatchActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, -1));

        jButtonLogOut.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(0, 102, 102));
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 200, -1));

        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/Update.jpeg"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 50, 30, 30));

        jLabelWallpaper2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWallpaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/8.jpeg"))); // NOI18N
        getContentPane().add(jLabelWallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        jLabelWallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/StudentInfo.png"))); // NOI18N
        getContentPane().add(jLabelWallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1980, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
           new StudentAdd().setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowDataActionPerformed

         
         
    }//GEN-LAST:event_jButtonShowDataActionPerformed

    private void jButtonStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStudentsActionPerformed
        new StudentInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStudentsActionPerformed

    private void jButtonTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeachersActionPerformed
        new TeacherInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTeachersActionPerformed

    private void jButtonStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffActionPerformed
        new StaffInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonStaffActionPerformed

    private void jButtonCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoursesActionPerformed
        new CourseInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCoursesActionPerformed

    private void jButtonBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatchActionPerformed
        new BatchInfo().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBatchActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        new SignIn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        new StudentModify().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBatch;
    private javax.swing.JButton jButtonCourses;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonShowData;
    private javax.swing.JButton jButtonStaff;
    private javax.swing.JButton jButtonStudents;
    private javax.swing.JButton jButtonTeachers;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JLabel jLabelWallpaper;
    private javax.swing.JLabel jLabelWallpaper1;
    private javax.swing.JLabel jLabelWallpaper2;
    private javax.swing.JLabel jLabelXIE;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableStudent;
    // End of variables declaration//GEN-END:variables
}
